name: Lint GitHub Action

run-name: ${{ github.actor }}님의 빌드 및 Lint 검사 🚀

on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: yarn
      - run: yarn build
      - run: yarn lint
